"""Add JSON fields for flexible parameter storage

Revision ID: 05784626a700
Revises: 51767e822a94
Create Date: 2025-09-30 17:08:01.614370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05784626a700'
down_revision: Union[str, Sequence[str], None] = '51767e822a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inferred_analytics', sa.Column('computed_metrics', sa.JSON(), nullable=True))
    op.add_column('inferred_analytics', sa.Column('algorithm_parameters', sa.JSON(), nullable=True))
    op.add_column('inferred_analytics', sa.Column('quality_indicators', sa.JSON(), nullable=True))
    op.add_column('raw_accelerometer_data', sa.Column('additional_sensors', sa.JSON(), nullable=True))
    op.add_column('raw_accelerometer_data', sa.Column('calibration_data', sa.JSON(), nullable=True))
    op.add_column('raw_accelerometer_data', sa.Column('processing_metadata', sa.JSON(), nullable=True))
    op.add_column('sensor_data', sa.Column('additional_data', sa.JSON(), nullable=True))
    op.add_column('sensor_data', sa.Column('device_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_data', 'device_metadata')
    op.drop_column('sensor_data', 'additional_data')
    op.drop_column('raw_accelerometer_data', 'processing_metadata')
    op.drop_column('raw_accelerometer_data', 'calibration_data')
    op.drop_column('raw_accelerometer_data', 'additional_sensors')
    op.drop_column('inferred_analytics', 'quality_indicators')
    op.drop_column('inferred_analytics', 'algorithm_parameters')
    op.drop_column('inferred_analytics', 'computed_metrics')
    # ### end Alembic commands ###
