"""Add raw accelerometer data and inferred analytics tables

Revision ID: 51767e822a94
Revises: ad6872ed4c14
Create Date: 2025-09-30 17:00:48.738951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51767e822a94'
down_revision: Union[str, Sequence[str], None] = 'ad6872ed4c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_accelerometer_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oxygen_concentrator_id', sa.String(), nullable=True),
    sa.Column('accel_x', sa.Float(), nullable=True),
    sa.Column('accel_y', sa.Float(), nullable=True),
    sa.Column('accel_z', sa.Float(), nullable=True),
    sa.Column('gyro_x', sa.Float(), nullable=True),
    sa.Column('gyro_y', sa.Float(), nullable=True),
    sa.Column('gyro_z', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Float(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_accelerometer_data_id'), 'raw_accelerometer_data', ['id'], unique=False)
    op.create_index(op.f('ix_raw_accelerometer_data_oxygen_concentrator_id'), 'raw_accelerometer_data', ['oxygen_concentrator_id'], unique=False)
    op.create_index(op.f('ix_raw_accelerometer_data_timestamp'), 'raw_accelerometer_data', ['timestamp'], unique=False)
    op.create_table('inferred_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oxygen_concentrator_id', sa.String(), nullable=True),
    sa.Column('cycle_time_seconds', sa.Float(), nullable=True),
    sa.Column('left_direction_seconds', sa.Float(), nullable=True),
    sa.Column('right_direction_seconds', sa.Float(), nullable=True),
    sa.Column('dominant_frequency_hz', sa.Float(), nullable=True),
    sa.Column('frequency_amplitude', sa.Float(), nullable=True),
    sa.Column('vibration_pattern', sa.String(), nullable=True),
    sa.Column('efficiency_score', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('operational_state', sa.String(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('analysis_window_minutes', sa.Integer(), nullable=True),
    sa.Column('data_points_analyzed', sa.Integer(), nullable=True),
    sa.Column('sensor_data_start_id', sa.Integer(), nullable=True),
    sa.Column('sensor_data_end_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('analysis_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sensor_data_end_id'], ['sensor_data.id'], ),
    sa.ForeignKeyConstraint(['sensor_data_start_id'], ['sensor_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inferred_analytics_id'), 'inferred_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_inferred_analytics_oxygen_concentrator_id'), 'inferred_analytics', ['oxygen_concentrator_id'], unique=False)
    op.create_index(op.f('ix_inferred_analytics_timestamp'), 'inferred_analytics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inferred_analytics_timestamp'), table_name='inferred_analytics')
    op.drop_index(op.f('ix_inferred_analytics_oxygen_concentrator_id'), table_name='inferred_analytics')
    op.drop_index(op.f('ix_inferred_analytics_id'), table_name='inferred_analytics')
    op.drop_table('inferred_analytics')
    op.drop_index(op.f('ix_raw_accelerometer_data_timestamp'), table_name='raw_accelerometer_data')
    op.drop_index(op.f('ix_raw_accelerometer_data_oxygen_concentrator_id'), table_name='raw_accelerometer_data')
    op.drop_index(op.f('ix_raw_accelerometer_data_id'), table_name='raw_accelerometer_data')
    op.drop_table('raw_accelerometer_data')
    # ### end Alembic commands ###
