"""add oxygen_concentrator_id column

Revision ID: 7237ecda09b2
Revises: 65fcbc105d09
Create Date: 2025-09-30 13:11:09.803758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7237ecda09b2'
down_revision: Union[str, Sequence[str], None] = '65fcbc105d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('oxygen_concentrator_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sensor_data_oxygen_concentrator_id'), 'sensor_data', ['oxygen_concentrator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_data_oxygen_concentrator_id'), table_name='sensor_data')
    op.drop_column('sensor_data', 'oxygen_concentrator_id')
    # ### end Alembic commands ###
