"""add comprehensive sensor data fields

Revision ID: ad6872ed4c14
Revises: 7237ecda09b2
Create Date: 2025-09-30 14:06:50.000890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6872ed4c14'
down_revision: Union[str, Sequence[str], None] = '7237ecda09b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('humidity', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('system_in_use', sa.Boolean(), nullable=True))
    op.add_column('sensor_data', sa.Column('oxygen_level', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('vibration_frequency', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('sensor_data', sa.Column('what3words_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_data', 'what3words_location')
    op.drop_column('sensor_data', 'longitude')
    op.drop_column('sensor_data', 'latitude')
    op.drop_column('sensor_data', 'vibration_frequency')
    op.drop_column('sensor_data', 'oxygen_level')
    op.drop_column('sensor_data', 'system_in_use')
    op.drop_column('sensor_data', 'humidity')
    op.drop_column('sensor_data', 'temperature')
    # ### end Alembic commands ###
